---
- name: Check if docker-compose file exists
  stat:
    path: "{{ app_dir }}/docker-compose.yml"
  register: app_dir_exists
  when: web_app_full_wipe | bool

- name: Wipe docker
  block:
    - name: Stop and remove Docker containers
      command: docker compose down
      args:
        chdir: "{{ app_dir }}"

    - name: Remove Docker volumes
      command: docker compose down -v
      args:
        chdir: "{{ app_dir }}"

    - name: Remove Docker network
      command: docker network prune -f

    - name: Remove Docker images
      command: docker image prune -a -f

    - name: Remove compose file
      file:
        path: "{{ app_dir }}/docker-compose.yml"
        state: absent

  when: web_app_full_wipe | bool and app_dir_exists.stat.exists
  tags:
    - wipe