version: '3.8'

networks:
  loki:

# x-deploy: &default-deploy
#   resources:
#     limits:
#       memory: 200M

x-logging: &common_logging
  driver: 'json-file'
  options:
    tag: '{{.ImageName}}|{{.ContainerName}}'
    max-size: '10M'
    max-file: '10'

services:
  app_python:
    build: ../app_python
    ports:
      - 5000:5000
    volumes:
      - ./app_python/visits_folder:/work_app/visits_folder:Z
    logging: *common_logging
    networks:
      - loki
    # deploy: *default-deploy
    healthcheck:
      test: ["CMD", "curl", "-f", "app_python:8000/health"]
      interval: 20s
      timeout: 10s
      retries: 3

  loki:
    image: grafana/loki:2.9.2
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging: *common_logging
    # deploy: *default-deploy

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
      - ./promtail.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    logging: *common_logging
    ports:
      - '9080:9080'
    # deploy: *default-deploy

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    networks:
      - loki
    logging: *common_logging
  # deploy: *default-deploy
  
  prometheus:
    image: prom/prometheus:v2.33.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    networks:
      - loki
    logging: *common_logging
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9090/status || exit 1"]
      interval: 20s
      timeout: 20s
      retries: 4
    # deploy: *default-deploy