---
- name: APT Update
  apt: 
    update_cache: yes
  tags: docker

- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install Docker
  import_tasks: install_docker.yml
  tags: docker

- name: Install docker-compose
  import_tasks: install_compose.yml
  tags: docker